src/WechatBribery/Models/Bribery.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WechatBribery.Models
{
    public class Bribery
    {
        public Guid Id { get; set; }

        public Guid ActivityId { get; set; }

        public virtual Activity Activity { get; set; }

        /// <summary>
        /// 领取时间
        /// </summary>
        public DateTime? ReceivedTime { get; set; }

        /// <summary>
        /// 以分为单位
        /// </summary>
        public long Price { get; set; }

        public string OpenId { get; set; }

        public string AvatarUrl { get; set; }

        public string NickName { get; set; }
    }
}

src/WechatBribery/Controllers/WeChatController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using WechatBribery.Hubs;
using WechatBribery.Models;
using static WechatBribery.Common.Wxpay;

namespace WechatBribery.Controllers
{
    public class WeChatController : BaseController
    {
        public static Dictionary<string, Activity> dic = new Dictionary<string, Activity>();

        public IActionResult Test()
        {
            HttpContext.Session.SetString("OpenId", "oHriRjg5tgcRD5f0jM7la5BMsC18");
            HttpContext.Session.SetString("AvatarUrl", "http://wx.qlogo.cn/mmopen/bVy2VQVTWzbUP1CS3aEHicwEpYrAUkHNwVibwHdnVuEC6wPhTs9LNepMW32U98CoJHOZahGibQONB2gnuIdvlVc7A/0");
            HttpContext.Session.SetString("Expire", DateTime.Now.AddDays(1).ToString());
            HttpContext.Session.SetString("Nickname", "あまみや ゆうこ");
            return Content("OK");
        }

        public string Test2()
        {
            return "Hello World";
        }

        public IActionResult Index(string id)
        {
            // 判断是否需要授权
            if (string.IsNullOrWhiteSpace(HttpContext.Session.GetString("OpenId")) || Convert.ToDateTime(HttpContext.Session.GetString("Expire")) <= DateTime.Now)
                return Redirect("https://open.weixin.qq.com/connect/oauth2/authorize?appid=" + Startup.Config["WeChat:AppId"] + "&redirect_uri=" + HttpContext.Request.Scheme + "://" + HttpContext.Request.Host + "/WeChatApi/ExchangeCode/" + id + "&response_type=code&scope=snsapi_userinfo");

            lock (this)
            {
                if (!dic.ContainsKey(id))
                {
                    var user = DB.Users.Single(x => x.UserName == id);
                    var activity = DB.Activities
                        .Include(x => x.Owner)
                        .Where(x => x.Owner.UserName == user.Id)
                        .LastOrDefault();
                    if (activity != null)
                        dic.Add(id, activity);
                }
            }

            if (!dic.ContainsKey(id))
                return View(null);
            else
                return View(dic[id]);
        }

        public IActionResult History()
        {
            var activity = DB.Activities.Last();
            var ret = DB.Briberies
                .Where(x => x.ActivityId == activity.Id && x.ReceivedTime.HasValue)
                .OrderByDescending(x => x.ReceivedTime)
                .Take(10)
                .ToList();
            return View(activity);
        }

        public IActionResult Exceeded()
        {
            return View();
        }

        public async Task<IActionResult> Shake(string id, [FromServices] IHubContext<BriberyHub> Hub)
        {
            // 判断是否需要授权
            if (string.IsNullOrWhiteSpace(HttpContext.Session.GetString("OpenId")) || Convert.ToDateTime(HttpContext.Session.GetString("Expire")) <= DateTime.Now)
                return Content("AUTH");
            
            // 微信平台要求15秒内不能给同一个用户再次发红包
            var cooldown = DateTime.Now.AddSeconds(-15);
            try
            {
                if (DB.Briberies.Count(x => x.OpenId == HttpContext.Session.GetString("OpenId") && x.ReceivedTime >= cooldown) > 0)
                    return Content("RETRY");
            }
            catch
            {
                return Content("RETRY");
            }

            // 判断是否中奖超过每日最大次数
            var beg = DateTime.Now.Date; 
            if (DB.Briberies.Count(x => x.OpenId == HttpContext.Session.GetString("OpenId") && x.ReceivedTime.HasValue && x.ReceivedTime.Value >= beg) >= Convert.ToInt32(Startup.Config["MaxPerDay"]))
                return Content("EXCEEDED");

            // 获取活动信息
            lock (this)
            {
                if (!dic.ContainsKey(id))
                {
                    var act = DB.Activities
                        .Include(x => x.Owner)
                        .FirstOrDefault(x => x.Owner.UserName == id && !x.End.HasValue);
                    if (act == null)
                        return Content("NO");
                    dic.Add(id, act);
                }
            }
            var activity = dic[id];

            // 参与人数缓存
            activity.Attend++;
            DB.Attach(activity);
            DB.SaveChanges();
            if (activity.Attend % 600 == 0)
                GC.Collect();

            // 抽奖
            var rand = new Random();
            var num = rand.Next(0, 10000);
            if (num < activity.Ratio * 10000)
            {
                var prize = DB.Briberies
                    .Where(x => x.ActivityId == activity.Id && !x.ReceivedTime.HasValue)
                    .OrderBy(x => Guid.NewGuid())
                    .FirstOrDefault();
                if (prize == null && DB.Briberies.Count(x => x.ActivityId == activity.Id) > 0) // 没有红包了
                {
                    activity.End = DateTime.Now;
                    DB.SaveChanges();
                    Hub.Clients.Group(activity.Id.ToString()).OnShaked(activity.Attend);
                    Hub.Clients.Group(activity.Id.ToString()).OnActivityEnd();
                    dic.Remove(id);
                    return Content("RETRY");
                }

                // 中奖发放红包
                prize.OpenId = HttpContext.Session.GetString("OpenId");
                prize.NickName = HttpContext.Session.GetString("Nickname");
                prize.AvatarUrl = HttpContext.Session.GetString("AvatarUrl");
                prize.ReceivedTime = DateTime.Now;
                DB.SaveChanges();

                // 微信转账
                await TransferMoneyAsync(prize.Id, HttpContext.Session.GetString("OpenId"), prize.Price, Startup.Config["WeChat:TransferDescription"]);
                Hub.Clients.Group(prize.ActivityId.ToString()).OnDelivered(new { time = prize.ReceivedTime, avatar = HttpContext.Session.GetString("AvatarUrl"), name = HttpContext.Session.GetString("Nickname"), price = prize.Price, id = HttpContext.Session.GetString("OpenId") });

                try
                {
                    DB.ChangeTracker.DetectChanges();
                    // 检查剩余红包数
                    if (DB.Briberies.Count(x => x.ActivityId == activity.Id && !x.ReceivedTime.HasValue) == 0 && DB.Briberies.Count(x => x.ActivityId == activity.Id) > 0)
                    {
                        activity.End = DateTime.Now;
                        DB.SaveChanges();
                        dic.Remove(id);
                        Hub.Clients.Group(activity.Id.ToString()).OnShaked(activity.Attend);
                        Hub.Clients.Group(activity.Id.ToString()).OnActivityEnd();
                    }
                }
                catch { }

                // 扣除红包费用
                activity.Owner.Balance -= prize.Price / 100.0;
                DB.ChangeTracker.DetectChanges();
                DB.SaveChanges();

                // 返回中奖信息
                return Content((prize.Price / 100.0).ToString("0.00"));
            }

            return Content("RETRY");
        }

        //public IActionResult ShakeCount(string id, long Count)
        //{
        //    // DB.Database.ExecuteSqlCommand("UPDATE \"Activities\" SET \"Attend\" = \"Attend\" + {0} WHERE \"AspNetUsers\".\"UserName\" = {1} AND \"End\" IS NULL", Count, id);
        //    return Content("ok");
        //}

        public IActionResult Bribery(Guid id)
        {
            var act = DB.Activities.Single(x => x.Id == id);
            return View(act);
        }
    }
}

src/WechatBribery/Views/Shared/Bribery.cshtml
@model Bribery
@{ 
    Layout = null;
}
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>摇一摇抽红包</title>
    <link href="~/styles/mobile.css" rel="stylesheet" />
    <script src="~/scripts/jQuery-2.1.4.min.js"></script>
    <script src="~/scripts/jquery.signalr-2.0.3.js"></script>
    <script src="~/signalr/hubs"></script>
    <style>
        .btn {
            margin: 0 auto;
            display: block;
            width: 220px;
            height: 50px;
            border-radius: 50px;
            text-align: center;
            color: #fed639;
            font-size: 18px;
            line-height: 50px;
            position: absolute;
            left: 50%;
            bottom: 100px;
            text-decoration: none;
            background: #dc201f;
            margin-left: -110px;
        }
    </style>
</head>
<body style="background: #000">
    <img src="~/images/drawn-2.png" style="width: 100%" />
    <div id="price" style="position:absolute; width: 300px; left: 50%; margin-left: -150px; text-align: center; color: #c11515; font-size: 22px;">￥@((Model.Price / 100.0).ToString("0.00"))</div>
    <a asp-action="Index" asp-controller="WeChat" class="btn">再来一次</a>
    <script>
        $(document).ready(function () {
            $('#price').css('top', $(window).width() * 18.2 / 22.08);
            $('.btn').css('top', $(window).width() * 24.2 / 22.08);
        });

        $(window).resize(function () {
            $('#price').css('top', $(window).width() * 18.2 / 22.08);
            $('.btn').css('top', $(window).width() * 24.2 / 22.08);
        });
    </script>
</body>
</html>

src/WechatBribery/Views/Shared/Exceeded.cshtml
@{ 
    Layout = null;
}
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>摇一摇抽红包</title>
    <script src="~/scripts/jQuery-2.1.4.min.js"></script>
    <script src="~/scripts/jquery.signalr-2.0.3.js"></script>
    <script src="~/signalr/hubs"></script>
</head>
<body>
    <p style="text-align:center"><img style="width: 70%; margin-top: 50px" src="~/images/cry.jpg" /></p>
    <p style="text-align:center">今天您已经抢到@(WechatBribery.Startup.Config["MaxPerDay"])个红包了，把好运留给别人吧！</p>
</body>
</html>

src/WechatBribery/Views/Shared/Prompt.cshtml
@model Prompt
@{ 
    ViewBag.Title = Model.Title;
}

<h2>@ViewBag.Title</h2>
<p>@Model.Details</p>

src/WechatBribery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>微信红包</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="~/styles/bootstrap.min.css">
    <link rel="stylesheet" href="~/styles/bootstrapValidator.min.css" />

    <!-- Bootstrap Responsive -->
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/styles/font-awesome.min.css" />
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/styles/ionicons.css" />
    <!-- jvectormap -->
    <link rel="stylesheet" href="~/styles/jquery-jvectormap-1.2.2.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/styles/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/styles/skins/_all-skins.min.css">
    <link rel="stylesheet" href="~/styles/bootstrap-colorpicker.css" />
    <link rel="stylesheet" href="~/styles/bootstrap-timepicker.css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="~/scripts/html5shiv.min.js"></script>
        <script src="~/scripts/respond.min.js"></script>
    <![endif]-->    
    <!-- jQuery 2.1.4 -->
    <script src="~/scripts/jQuery-2.1.4.min.js"></script>
    <script src="~/scripts/jquery.signalr-2.0.3.js"></script>
    <script src="~/signalr/hubs"></script>
    <style type="text/css">
        .infotitle {
            color: rgb(119,119,119);
        }

        .fcontent {
            height: 200px;
        }

        .must2 {
            color: #FF88FF;
        }

        .must3 {
            color: #FF88FF;
            font-size: 8px;
        }

        .table-title {
            background-color: rgb(60,141,188);
        }

        .infolb {
            color: white;
        }
    </style>
    <link href="~/styles/style.css" rel="stylesheet" />
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

        <header class="main-header">

            <!-- Logo -->
            <a asp-action="Index" asp-controller="Home" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>@ViewBag.SmallTitle</b></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>微信红包</b></span>
            </a>

            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- Control Sidebar Toggle Button -->
                        <li>
                            <a href="javascript:$('#Logout').submit()">退出</a>
                        </li>
                    </ul>
                    <form asp-action="Logout" asp-controller="Account" id="Logout"></form>
                </div>

            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/images/person.png" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p><i class="fa fa-user text-warning"></i>@User.Current.UserName</p>
                        <p><i class="fa fa-star text-success">余额</i><i class="text-danger">￥@((User.Current.Balance).ToString("0.00"))</i></p>
                    </div>
                </div>
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="header" style="color:white;">红包管理</li>
                    <li class="active treeview">
                        <a href="#">
                            <i class="fa fa-files-o"></i> <span>红包管理</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li><a asp-action="Index" asp-controller="Home"><i class="fa fa-circle-o"></i>基本信息</a></li>
                            <li><a asp-action="Deliver" asp-controller="Home"><i class="fa fa-circle-o"></i>发放红包</a></li>
                            <li><a asp-action="History" asp-controller="Home"><i class="fa fa-circle-o"></i>发放历史</a></li>
                        </ul>
                    </li>
                    @if (User.IsInRole("Root"))
                    {
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-star-o"></i>
                                <span>系统管理</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a asp-action="Index" asp-controller="Account"><i class="fa fa-circle-o"></i> 用户列表</a></li>
                                <li><a asp-action="Create" asp-controller="Account"><i class="fa fa-circle-o"></i> 创建用户</a></li>
                            </ul>
                        </li>
                    }
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-star-o"></i>
                            <span>我的账户</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li><a asp-action="Password" asp-controller="Account"><i class="fa fa-circle-o"></i> 修改密码</a></li>
                            <li><a asp-action="Profile" asp-controller="Account"><i class="fa fa-circle-o"></i> 修改商户信息</a></li>
                            <li><a href="javascript:$('#frmLogout').submit();"><i class="fa fa-circle-o"></i> 注销登录</a></li>
                        </ul>
                    </li>
                </ul>
            </section>
            <form id="frmLogout" asp-action="Logout" asp-controller="Account" method="post"></form>
            <!-- /.sidebar -->
        </aside>
        <div>
            <section>
                <div class="content-wrapper">
                    <section class="content">
                        @RenderBody()
                    </section>
                </div>
            </section>
        </div>

        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b id="current-time"></b>
            </div>
            <strong>
                Copyright &copy; @DateTime.Now.Year
                <a href="http://www.1234.sh" target="_blank">Pomelo Foundation</a>.
            </strong> All rights reserved.
        </footer>


    </div><!-- ./wrapper -->
    <!-- Bootstrap 3.3.5 -->
    <script src="~/scripts/bootstrap.min.js"></script>
    <script src="~/scripts/bootstrapValidator.min.js"></script>
    <!-- FastClick -->
    <script src="~/scripts/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/scripts/app.js"></script>
    <script src="~/scripts/daterangepicker.js"></script>
    <script src="~/scripts/bootstrap-colorpicker.js"></script>
    <script src="~/scripts/bootstrap-timepicker.js"></script>
    <!-- Sparkline -->
    <script src="~/scripts/jquery.sparkline.min.js"></script>
    <!-- jvectormap -->
    <script src="~/scripts/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/scripts/jquery-jvectormap-world-mill-en.js"></script>
    <!-- SlimScroll 1.3.0 -->
    <script src="~/scripts/jquery.slimscroll.min.js"></script>
    <!-- ChartJS 1.0.1 -->
    <script src="~/scripts/Chart.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/scripts/pages/dashboard2.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/scripts/demo.js"></script>
</body>
</html>